#!/usr/bin/env node
/**
 * Sync warpee/openapi.json + shoutout/openapi.json from the LIVE services.
 *
 * Roadmap item 18, Track B3 (see gmfc101/internal_docs/dual-rail-api-charter.md
 * §4.3). The charter's decision: the served /openapi.json on each API is now
 * the source of truth (agents consume that, not this repo) — this repo holds
 * a DERIVED copy. Nobody should hand-edit warpee/openapi.json or
 * shoutout/openapi.json; edit the service (gmfc101's core/openapi_doc.py, or
 * gm-farcaster's apps/api/src/lib/discovery.ts) and re-run this script.
 *
 * Two modes:
 *   npm run sync:openapi        fetch, validate, write the derived files.
 *   npm run sync:openapi:check  fetch, validate, diff against what's
 *                                committed, exit nonzero on drift. This is
 *                                what makes drift DETECTABLE — run it in a
 *                                scheduled job once this has been run
 *                                manually a few times (see the charter, B3
 *                                step 3 — not built yet, no CI exists in any
 *                                of the three repos today).
 *
 * Every fetched document is run through mppx/discovery's own validate()
 * before anything is written — the same validator gmfc101 and gm-farcaster
 * already run their live documents through, so this script is a second,
 * independent check that catches drift (a service regressing after this
 * script last ran), not just a copier.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { validate } from 'mppx/discovery';

const REPO_ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const SOURCES = [
  {
    name: 'warpee',
    url: 'https://api.gmfarcaster.com/v1/openapi.json',
    outPath: path.join(REPO_ROOT, 'warpee', 'openapi.json'),
  },
  {
    name: 'shoutout',
    url: 'https://gateway.gmfarcaster.com/openapi.json',
    outPath: path.join(REPO_ROOT, 'shoutout', 'openapi.json'),
  },
];

const GENERATED_NOTE =
  'Generated by scripts/sync-openapi.mjs from the live service — do not edit ' +
  'directly. Edit the service (gmfc101/core/openapi_doc.py for warpee, ' +
  'gm-farcaster/apps/api/src/lib/discovery.ts for shoutout) and re-run ' +
  '`npm run sync:openapi`.';

async function fetchDocument(url) {
  const res = await fetch(url, { headers: { Accept: 'application/json' } });
  if (!res.ok) {
    throw new Error(`GET ${url} -> ${res.status} ${res.statusText}`);
  }
  return res.json();
}

/** Wrap the live document with sync provenance. `syncedAt` is a parameter
 * (not computed inside) so buildGeneratedDoc is easy to call with a fixed
 * value when comparing for drift — see stripSyncedAt / --check below. */
function buildGeneratedDoc(liveDoc, sourceUrl, syncedAt) {
  return {
    ...liveDoc,
    'x-generated': {
      note: GENERATED_NOTE,
      source: sourceUrl,
      syncedAt,
    },
  };
}

/** Drop the volatile timestamp before comparing two generated documents —
 * otherwise --check would report drift on every run just because the clock
 * moved, even with a byte-identical live document underneath. */
function withoutSyncedAt(doc) {
  const clone = structuredClone(doc);
  if (clone['x-generated']) delete clone['x-generated'].syncedAt;
  return clone;
}

function serialize(doc) {
  return JSON.stringify(doc, null, 2) + '\n';
}

async function processSource(source, { check }) {
  console.log(`\n=== ${source.name} (${source.url}) ===`);

  let liveDoc;
  try {
    liveDoc = await fetchDocument(source.url);
  } catch (err) {
    console.error(`  FETCH FAILED: ${err.message}`);
    return { ok: false };
  }

  let errors;
  try {
    errors = validate(liveDoc);
  } catch (err) {
    console.error(`  VALIDATE THREW: ${err.message}`);
    return { ok: false };
  }

  const hardErrors = errors.filter((e) => e.severity === 'error');
  const warnings = errors.filter((e) => e.severity !== 'error');
  for (const w of warnings) console.warn('  validation warning:', w);
  if (hardErrors.length > 0) {
    console.error(`  VALIDATION FAILED (${hardErrors.length} error(s)) — not writing/checking this file:`);
    for (const e of hardErrors) console.error('   ', JSON.stringify(e));
    return { ok: false };
  }
  console.log(`  validate(): clean (${warnings.length} warning(s))`);

  // syncedAt is fixed at "now" once per invocation of this script for both
  // sources, not fetched-and-forgotten per source, so a single sync run
  // stamps both files identically.
  const generated = buildGeneratedDoc(liveDoc, source.url, processSource.syncedAt);

  if (check) {
    let committed;
    try {
      committed = JSON.parse(await readFile(source.outPath, 'utf8'));
    } catch (err) {
      console.error(`  DRIFT: ${source.outPath} is missing or unreadable (${err.message})`);
      return { ok: false };
    }
    const freshNormalized = serialize(withoutSyncedAt(generated));
    const committedNormalized = serialize(withoutSyncedAt(committed));
    if (freshNormalized !== committedNormalized) {
      console.error(`  DRIFT: ${source.outPath} does not match the live service.`);
      console.error('  Run `npm run sync:openapi` to update it.');
      return { ok: false };
    }
    console.log(`  ${source.outPath} matches the live service.`);
    return { ok: true };
  }

  await writeFile(source.outPath, serialize(generated), 'utf8');
  console.log(`  wrote ${source.outPath}`);
  return { ok: true };
}

async function main() {
  const check = process.argv.includes('--check');
  processSource.syncedAt = new Date().toISOString();

  const results = [];
  for (const source of SOURCES) {
    results.push(await processSource(source, { check }));
  }

  const failed = results.some((r) => !r.ok);
  if (failed) {
    console.error(`\n${check ? 'Drift detected' : 'Sync failed'} — see above.`);
    process.exit(1);
  }
  console.log(`\nAll sources ${check ? 'match the live services' : 'synced'}.`);
}

main().catch((err) => {
  console.error('sync-openapi.mjs crashed:', err);
  process.exit(1);
});
